### ISSUE TITLE
Dummy gateway not showing up in WooCommerce checkout blocks

### ISSUE THREAD

**Issue by AaronBowie** [woocommerce/woocommerce-gateway-dummy#12]
I noticed that the plugin is not showing up in the WooCommerce checkout blocks.
This is with and without the WooCommerce Blocks plugin enabled.

WooCommerce version 7.0
WP version 6.0.2

**Comment by jimjasson** [comment]
Hey @AaronBowie, 

Thank you for reporting this! 

I tested both with an existing site and a brand-new site and I confirmed that Dummy Payments showed up in the block-based checkout (both with WooCommerce v7 and with WooCommerce v7 + the Blocks plugin). 

![Markup on 2022-10-17 at 10:44:06](https://user-images.githubusercontent.com/25955483/196118339-6e157e2e-2876-4b91-b92d-70c8691dd113.png)

Can you please check if this issue persists when only WooCommerce and Dummy Payments are active and a default WordPress theme, such as Storefront, is active? 

If the issue persists, then could you give us some more details about this issue? Do you follow any specific steps to replicate it? Do you see any errors in the site logs or in the console? Is there any publicly accessible site where we can view this behavior?

**Comment by wzul** [comment]
To anyone who are looking for answer why

This happened because WordPress will look for the script in: 
```
/wp-content/plugins/woocommerce-gateway-dummy/assets/js/frontend/blocks.js
```

However, if you are cloning this repository, the file is not available there as it needs to be compiled and hence **Dummy gateway not showing up in WooCommerce checkout blocks**.

So, there is 2 solution:

1. Download the compiled version from release tags at: https://github.com/woocommerce/woocommerce-gateway-dummy/releases (make sure to download from the assets and choose **woocommerce-gateway-dummy.zip** (not source code). OR;
2. Clone this repository and run `$ npm install` and `$ npm run build` in your terminal as per documented in: https://developer.woocommerce.com/2022/05/20/hiding-shipping-and-payment-options-in-the-cart-and-checkout-blocks/

**Comment by jimjasson** [comment]
Good point @wzul ! Added the building instructions in the plugin's readme file.
