### ISSUE TITLE
Update node/npm engines

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gateway-dummy#32]
`@wordpress/scripts` requires node 18+. `npm run packages-update` produces the following

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@wordpress/scripts@27.5.0',
npm WARN EBADENGINE   required: { node: '>=18', npm: '>=6.14.4' },
npm WARN EBADENGINE   current: { node: 'v16.19.1', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@wordpress/dependency-extraction-webpack-plugin@5.5.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.19.1', npm: '8.19.3' }
npm WARN EBADENGINE }
```

[`.nvmrc`](https://github.com/woocommerce/woocommerce-gateway-dummy/blob/master/.nvmrc) is Node 16.

**Comment by dakota** [comment]
@helgatheviking Thank you for reporting this! 

It looks like the issue is that the `npm run package-update` changes the constraint for the `@wordpress/scripts` package to `^27.6.0` and forces it to be upgraded without any regard for other constraints in place (Such as the Node version).

We will schedule some time to look into upgrading the package and testing on Node 18, in the meantime skip the `npm run package-update` step.

**Comment by PanosSynetos** [comment]
Hey @helgatheviking - We're planning to upgrade this to node 20, to be on the same page as WooCommerce (which recently upgraded)

We'll ping you when done
