### ISSUE TITLE
Not working with latest woocommerce 8.8.2.

### ISSUE THREAD

**Issue by tamas-pim** [woocommerce/woocommerce-gateway-dummy#34]
Hi, I cloned the plugin and activated it, but the dummy payment option is still not visible as a checkout option in the block view. It is really hard to debug why our payment plugin is not working, that's why I tried this dummy gateway. Also, it looks like from the fronted console logs, that block.js does not exist. I tried to change the script path to index.js.
Also, the payment option is visible in the page editor for some reason. I don't know why its not on the checkout page.

**Comment by jimjasson** [comment]
Hey @tamas-pim, 

Thank you for reporting this! 

I had a look at my local site, which uses the latest WooCommerce version, and confirmed that the Dummy Payments gateway is visible in the checkout page:

![Markup on 2024-04-19 at 11:50:55](https://github.com/woocommerce/woocommerce-gateway-dummy/assets/25955483/97b3e1d3-b427-401b-849f-f7a351d6fd0a)

Can you please make sure that you have downloaded the **built** version of the extension?  Here's a [direct download link](https://github.com/woocommerce/woocommerce-gateway-dummy/releases/download/1.0.8/woocommerce-gateway-dummy.zip).

If you are using the built version, can you please navigate to WooCommerce > Settings > Payments and ensure that Dummy Payments is enabled there?

![Markup on 2024-04-19 at 11:54:52](https://github.com/woocommerce/woocommerce-gateway-dummy/assets/25955483/f4430984-c3d1-40c9-b81a-a92c0d6f483a)

If the gateway is still not visible, then there is a chance that this issue is triggered by a theme or plugin conflict. 

Could you please: 
- switch your active theme back to a default WordPress theme, such as Twenty Twenty Four or Storefront and;
- deactivate all plugins except for WooCommerce and Dummy Payments?

If the issue still persists, then could you please share with me any errors you see either in the console or the server logs?

**Comment by jimjasson** [comment]
Hey @tamas-pim, 

Since it is been a while since we last heard from you on this issue and the issue you reported is very similar to: https://github.com/woocommerce/woocommerce-gateway-dummy/issues/35 which has now been fixed, I will mark this as closed. Feel free to re-open it if you would like to share more details! :)
